name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:


    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change working directory and run commands
      run: cd kwetter-twitter-clone

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.14.2

        
    - name: Install dependencies
      working-directory: ./kwetter-twitter-clone
      run: npm install

    - name: Build
      working-directory: ./kwetter-twitter-clone
      run: npm run build

    - name: Deploy
      run: |
        # Add your deployment commands here
