name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:


    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change working directory and run commands
      run: cd kwetter-twitter-clone

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

        
    - name: Install dependencies
      run:  cd kwetter-twitter-clone
        npm install

    - name: Build
      run: cd kwetter-twitter-clone
       npm run build

    - name: Test
      run: cd kwetter-twitter-clone
        npm test

    - name: Deploy
      run: |
        # Add your deployment commands here
